voting-app:
  build: ./voting/.
  volumes:
    - ./voting:/app
  ports:
    - "5000:80"
  links:
    - "redis"

redis:
  image: redis
  ports: ["6379"]

worker:
  build: ./worker
  links:
    - "redis"
    - "db"

db:
  image: postgres
  volumes:
    - "myvolume:/var/lib/postgresql/data"

result-app:
  build: ./result/.
  volumes:
    - ./result:/app
  ports:
    - "5001:80"
  links:
    - "db"
